-- 创建部门数据表
CREATE TABLE tbl_department(
  id INT(11) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  dept_no MEDIUMINT UNSIGNED NOT NULL DEFAULT 0,
  dept_name VARCHAR(20) NOT NULL DEFAULT ""
)ENGINE=INNODB DEFAULT CHARSET=UTF8 AUTO_INCREMENT=1;



-- 创建员工数据表
CREATE TABLE tbl_employee(
  id INT(11) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	emp_no INT(10) UNSIGNED NOT NULL DEFAULT 0,
	emp_name VARCHAR(20) NOT NULL DEFAULT "",
	emp_age TINYINT(3) NOT NULL DEFAULT 0,
	emp_post VARCHAR(15) NOT NULL DEFAULT "",
	dept_no MEDIUMINT UNSIGNED NOT NULL DEFAULT 0
)ENGINE=INNODB DEFAULT CHARSET=UTF8 AUTO_INCREMENT=1;